<?php
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$easypack24Data = $this->getQuote()->getEasypack24Data();
	$_rate = $this->getRate();

    //Mage::log(var_export($_SESSION, 1) . '------', null, 'session.log');

    $machines = Mage::helper('easypack24/data')->connectEasypack24(
        array(
            'url' => Mage::getStoreConfig('carriers/easypack24/api_url').'machines',
            'methodType' => 'GET',
            'params' => array(
                'town' => $this->getQuote()->getShippingAddress()->getCity(),
                'post_code' => $this->getQuote()->getShippingAddress()->getPostcode() // post code has priority the town
            )
        )
    );
    //Mage::log(var_export($machines, 1) . '------', null, 'machines.log');

    $parcelTargetMachinesId = array();
    $parcelTargetMachinesDetail = array();
    if(is_array(@$machines['result'])){
        foreach($machines['result'] as $key => $machine){
            $parcelTargetMachinesId[$machine->id] = $machine->id.', '.@$machine->address->city.', '.@$machine->address->street;
            $parcelTargetMachinesDetail[$machine->id] = array(
                'id' => $machine->id,
                'address' => array(
                    'building_number' => @$machine->address->building_number,
                    'flat_number' => @$machine->address->flat_number,
                    'post_code' => @$machine->address->post_code,
                    'province' => @$machine->address->province,
                    'street' => @$machine->address->street,
                    'city' => @$machine->address->city
                )
            );
        }
        Mage::getSingleton('checkout/session')->setParcelTargetMachinesDetail($parcelTargetMachinesDetail);
    }


?>
<!--<script type="text/javascript">-->
<!--    function user_function(value) {-->
<!--        var address = value.split(';');-->
<!--        //document.getElementById('town').value=address[1];-->
<!--        //document.getElementById('street').value=address[2]+address[3];-->
<!--        var box_machine_name = document.getElementById('name').value;-->
<!--        var box_machine_town = document.value=address[1];-->
<!--        var box_machine_street = document.value=address[2];-->
<!---->
<!---->
<!--        var is_value = 0;-->
<!--        document.getElementById('shipping_easypack24').value = box_machine_name;-->
<!--        var shipping_easypack24 = document.getElementById('shipping_easypack24');-->
<!---->
<!--        for(i=0;i<shipping_easypack24.length;i++){-->
<!--            if(shipping_easypack24.options[i].value == document.getElementById('name').value){-->
<!--                shipping_easypack24.selectedIndex = i;-->
<!--                is_value = 1;-->
<!--            }-->
<!--        }-->
<!---->
<!--        if (is_value == 0){-->
<!--            shipping_easypack24.options[shipping_easypack24.options.length] = new Option(box_machine_name+','+box_machine_town+','+box_machine_street, box_machine_name);-->
<!--            shipping_easypack24.selectedIndex = shipping_easypack24.length-1;-->
<!--        }-->
<!--    }-->
<!--</script>-->
<!--<script type="text/javascript" src="https://geowidget.inpost.co.uk/dropdown.php?field_to_update=name&field_to_update2=address&user_function=user_function"></script>-->

<ul class="form-list" id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">
    <li>
        <!--<label for="--><?php //echo @$_code ?><!--_target_box_machine" class="required"><em>*</em>--><?php //echo $this->__('Choose Target Box Machine:') ?><!--</label>-->
        <span class="input-box">
            <select class="required-entry" id="shipping_easypack24" name="shipping_easypack24[parcel_target_machine_id]">
                <option value='' <?php if(@$easypack24Data['parcel_target_machine_id'] == ''){ echo "selected=selected";} ?>><?php echo $this->__('Select Machine..');?></option>
                <?php foreach($parcelTargetMachinesId as $key => $parcelTargetMachineId): ?>
                    <option value='<?php echo $key ?>' <?php if($easypack24Data['parcel_target_machine_id'] == $parcelTargetMachineId){ echo "selected=selected";} ?>><?php echo $parcelTargetMachineId;?></option>
                <?php endforeach; ?>
            </select>
            <input type="hidden" id="name" name="name" disabled="disabled" />
            <input type="hidden" id="box_machine_town" name="box_machine_town" disabled="disabled" />
            <input type="hidden" id="address" name="address" disabled="disabled" />
        </span>
        <a href="#" onclick="openMap(); return false;">Map</a>
    </li>
</ul>

