<script type="text/javascript" src="https://geowidget.inpost.co.uk/dropdown.php?field_to_update=name&field_to_update2=address&user_function=user_function"></script>
<script type="text/javascript">
    function user_function(value) {
        var address = value.split(';');
        //document.getElementById('town').value=address[1];
        //document.getElementById('street').value=address[2]+address[3];
        var box_machine_name = document.getElementById('name').value;
        var box_machine_town = document.value=address[1];
        var box_machine_street = document.value=address[2];


        var is_value = 0;
        document.getElementById('shipping_easypack24').value = box_machine_name;
        var shipping_easypack24 = document.getElementById('shipping_easypack24');

        for(i=0;i<shipping_easypack24.length;i++){
            if(shipping_easypack24.options[i].value == document.getElementById('name').value){
                shipping_easypack24.selectedIndex = i;
                is_value = 1;
            }
        }

        if (is_value == 0){
            shipping_easypack24.options[shipping_easypack24.options.length] = new Option(box_machine_name+','+box_machine_town+','+box_machine_street, box_machine_name);
            shipping_easypack24.selectedIndex = shipping_easypack24.length-1;
        }
    }
</script>

<?
$easypack24Data = Mage::registry('easypack24_data');
?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Edit parcel')?></h3></td>
            <td class="a-right">
                <button onclick="history.back();" class="button" title="<?php echo $this->__('Back') ?>" type="button"><span><span><?php echo $this->__('Back') ?></span></span></button>
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Parcel update</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="<?=$this->getUrl('*/*/save')?>">
        <input type="hidden" name="parcel_id" value="<?php echo $easypack24Data['parcel_id']; ?>" />
        <input type="hidden" name="id" value="<?php echo $easypack24Data['id']; ?>" />
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Parcel detail')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Parcel box machine')?> <span class="required">*</span></td>
                    <td class="input-ele">
                        <select class="required-entry" id="shipping_easypack24" name="parcel_target_machine_id" <?php echo Mage::registry('disabledMachines'); ?>>
                            <option value='' <?php if(@$easypack24Data['parcel_target_machine_id'] == ''){ echo "selected=selected";} ?>><?php echo Mage::registry('defaultMachine');?></option>
                            <?php foreach(Mage::registry('parcelTargetMachinesId') as $key => $parcelTargetMachine): ?>
                            <option value='<?php echo $key ?>' <?php if($easypack24Data['parcel_target_machine_id'] == $key){ echo "selected=selected";} ?>><?php echo $parcelTargetMachine;?></option>
                            <?php endforeach; ?>
                        </select>
                        <?php if(Mage::registry('disabledMachines') != 'disabled'): ?>
                            <input type="hidden" id="name" name="name" disabled="disabled" />
                            <input type="hidden" id="box_machine_town" name="box_machine_town" disabled="disabled" />
                            <input type="hidden" id="address" name="address" disabled="disabled" />
                            <a href="#" onclick="openMap(); return false;">Map</a>
                            &nbsp|&nbsp<input type="checkbox" name="show_all_machines"> Show terminals in other cities
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('Parcel description')?> <span class="required">*</span></td>
                    <td class="input-ele"><textarea name="parcel_description" rows="10" cols="35"><?php echo $easypack24Data['parcel_description']; ?></textarea></td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('Parcel size')?> <span class="required">*</span></td>
                    <td class="input-ele">
                        <select class="required-entry" id="parcel_size" name="parcel_size" <?php echo Mage::registry('disabledParcelSize'); ?>>
                            <option value='' <?php if($easypack24Data['parcel_size'] == ''){ echo "selected=selected";} ?>><?php echo Mage::registry('defaultParcelSize');?></option>
                            <option value='A' <?php if($easypack24Data['parcel_size'] == 'A'){ echo "selected=selected";} ?>>A</option>
                            <option value='B' <?php if($easypack24Data['parcel_size'] == 'B'){ echo "selected=selected";} ?>>B</option>
                            <option value='C' <?php if($easypack24Data['parcel_size'] == 'C'){ echo "selected=selected";} ?>>C</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('Parcel status')?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="parcel_status" value="<?php echo $easypack24Data['parcel_status']; ?>" <?php ?>/></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');

    jQuery(document).ready(function(){
        jQuery('input[type="checkbox"][name="show_all_machines"]').click(function(){
            var machines_list_type = jQuery(this).is(':checked');

            if(machines_list_type == true){
                //alert('all machines');
                var machines = {
                    '' : 'Select Machine..',
                <?php foreach(Mage::registry('parcelTargetAllMachinesId') as $key => $parcelTargetAllMachineId): ?>
                    '<?php echo $key ?>' : '<?php echo addslashes($parcelTargetAllMachineId) ?>',
                    <?php endforeach; ?>
                };
            }else{
                //alert('criteria machines');
                var machines = {
                    '' : 'Select Machine..',
                <?php foreach(Mage::registry('parcelTargetMachinesId') as $key => $parcelTargetMachineId): ?>
                    '<?php echo $key ?>' : '<?php echo addslashes($parcelTargetMachineId) ?>',
                    <?php endforeach; ?>
                };
            }

            jQuery('#shipping_easypack24 option').remove();
            jQuery.each(machines, function(val, text) {
                jQuery('#shipping_easypack24').append(
                        jQuery('<option></option>').val(val).html(text)
                );
            });
        });
    });
</script>