<?php
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$easypack24Data = $this->getQuote()->getEasypack24Data();
	$_rate = $this->getRate();

    //Mage::log(var_export($_SESSION, 1) . '------', null, 'session.log');

    $allMachines = Mage::helper('easypack24/data')->connectEasypack24(
        array(
            'url' => Mage::getStoreConfig('carriers/easypack24/api_url').'machines',
            'methodType' => 'GET',
            'params' => array(
            )
        )
    );

    $parcelTargetAllMachinesId = array();
    $parcelTargetAllMachinesDetail = array();
    $machines = array();
    if(is_array(@$allMachines['result']) && !empty($allMachines['result'])){
        foreach($allMachines['result'] as $key => $machine){
            $parcelTargetAllMachinesId[$machine->id] = $machine->id.', '.@$machine->address->city.', '.@$machine->address->street;
            $parcelTargetAllMachinesDetail[$machine->id] = array(
                'id' => $machine->id,
                'address' => array(
                    'building_number' => @$machine->address->building_number,
                    'flat_number' => @$machine->address->flat_number,
                    'post_code' => @$machine->address->post_code,
                    'province' => @$machine->address->province,
                    'street' => @$machine->address->street,
                    'city' => @$machine->address->city
                )
            );
            if($machine->address->post_code == $this->getQuote()->getShippingAddress()->getPostcode()){
                $machines[$key] = $machine;
                continue;
            }elseif($machine->address->city == $this->getQuote()->getShippingAddress()->getCity()){
                $machines[$key] = $machine;
            }
        }
        Mage::getSingleton('checkout/session')->setParcelTargetAllMachinesDetail($parcelTargetAllMachinesDetail);
    }

    //Mage::log(var_export($machines, 1) . '------', null, 'machines.log');
    //Mage::log(var_export($allMachines, 1) . '------', null, 'all_machines.log');

    $parcelTargetMachinesId = array();
    $parcelTargetMachinesDetail = array();
    $defaultSelect = $this->__('Select Machine..');
    if(is_array(@$machines) && !empty($machines)){
        foreach($machines as $key => $machine){
            $parcelTargetMachinesId[$machine->id] = $machine->id.', '.@$machine->address->city.', '.@$machine->address->street;
            $parcelTargetMachinesDetail[$machine->id] = array(
                'id' => $machine->id,
                'address' => array(
                    'building_number' => @$machine->address->building_number,
                    'flat_number' => @$machine->address->flat_number,
                    'post_code' => @$machine->address->post_code,
                    'province' => @$machine->address->province,
                    'street' => @$machine->address->street,
                    'city' => @$machine->address->city
                )
            );
        }
        Mage::getSingleton('checkout/session')->setParcelTargetMachinesDetail($parcelTargetMachinesDetail);
    }else{
        $defaultSelect = $this->__('no terminals in your city');
    }
    //Mage::log(var_export($parcelTargetAllMachinesDetail, 1) . '------', null, 'all_machines.log');

    $user_phone = $this->getQuote()->getShippingAddress()->getTelephone();
    if(!preg_match('/^[1-9]{1}\d{8}$/', $user_phone)){
        $user_phone = null;
    }

?>
<ul class="form-list" id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">
    <li>
        <!--<label for="--><?php //echo @$_code ?><!--_target_box_machine" class="required"><em>*</em>--><?php //echo $this->__('Choose Target Box Machine:') ?><!--</label>-->
        <span class="input-box">
            <select class="required-entry" id="shipping_easypack24" name="shipping_easypack24[parcel_target_machine_id]">
                <option value='' <?php if(@$easypack24Data['parcel_target_machine_id'] == ''){ echo "selected=selected";} ?>><?php echo $defaultSelect;?></option>

                <?php foreach($parcelTargetMachinesId as $key => $parcelTargetMachineId): ?>
                    <option value='<?php echo $key ?>' <?php if($easypack24Data['parcel_target_machine_id'] == $parcelTargetMachineId){ echo "selected=selected";} ?>><?php echo $parcelTargetMachineId;?></option>
                <?php endforeach; ?>

            </select>
            <input type="hidden" id="name" name="name" disabled="disabled" />
            <input type="hidden" id="box_machine_town" name="box_machine_town" disabled="disabled" />
            <input type="hidden" id="address" name="address" disabled="disabled" />
            <a href="#" onclick="openMap(); return false;">Map</a>
            &nbsp|&nbsp<input type="checkbox" name="show_all_machines"> Show terminals in other cities
        </span>
    </li>
    <li>
        <label for="<?php echo $_code ?>_receiver_phone" class="required"><em>*</em><?php echo $this->__("Mobile e.g. 523045856") ?></label>
        <span class="input-box">
        	(07) <input type='text' name='shipping_easypack24[receiver_phone]' id="<?php echo $_code ?>_phone" title="mobile /^[1-9]{1}\d{8}$/" class='required-entry validate-number validate-length minimum-length-9 maximum-length-9 easypack24_phone' value='<?php echo $easypack24Data['receiver_phone']?$easypack24Data['receiver_phone']:$user_phone?>' />
        </span>
    </li>
</ul>

<script type="text/javascript">

jQuery(document).ready(function(){
    jQuery('input[type="checkbox"][name="show_all_machines"]').click(function(){
        var machines_list_type = jQuery(this).is(':checked');

        if(machines_list_type == true){
            //alert('all machines');
            var machines = {
                '' : 'Select Machine..',
            <?php foreach($parcelTargetAllMachinesId as $key => $parcelTargetAllMachineId): ?>
                '<?php echo $key ?>' : '<?php echo addslashes($parcelTargetAllMachineId) ?>',
            <?php endforeach; ?>
            };
        }else{
            //alert('criteria machines');
            var machines = {
                '' : 'Select Machine..',
            <?php foreach($parcelTargetMachinesId as $key => $parcelTargetMachineId): ?>
                '<?php echo $key ?>' : '<?php echo addslashes($parcelTargetMachineId) ?>',
            <?php endforeach; ?>
            };
        }

        jQuery('#shipping_easypack24 option').remove();
        jQuery.each(machines, function(val, text) {
            jQuery('#shipping_easypack24').append(
                    jQuery('<option></option>').val(val).html(text)
            );
        });
    });
});


</script>